use_frameworks!

target 'SPHttpRequestLibrary_Example' do
  pod 'SPHttpRequestLibrary', :path => '../'

  target 'SPHttpRequestLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
